version: '3'

services:
  db_postgres:
    image: 'postgres:13.1-alpine'
    container_name: db_postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booking_room
  db_mongo:
    image: 'mongo'
    container_name: db_mongo
    ports:
      - 27017:27017
  app:
    image: 'docker_booking_meeting_room:latest'
    container_name: app
    build:
      context: .
    depends_on:
      - db_postgres
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - 8080:8080